config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get 'search' => 'search#index'
  get 'search/search' => 'search#search'

  resources :auctions, only: [:index, :create, :destroy]

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  validates :name, :url, presence: true
  validates :url, uniqueness: true
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def index
    @auctions = Auction.all
  end
  def create
    auction = Auction.new(auction_params)
    if auction.save
      render json: {status: "saved"}, status: 201
    else
      render json: { errors: auction.errors.full_messages }, status: 422
    end
  end
  def destroy
    begin
      auction = Auction.find(params[:id])
      auction.delete
      flash[:success] = "Auction deleted!"
    rescue
      flash[:danger] = "Couldn't delete auction with id #{params[:id]}!"
    end
    redirect_to auctions_path
  end

  private

  def auction_params
    params.require(:auction).permit(:name, :url)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @categories = [['All',nil]]
    @categories += Category.where(parent: 0).order(:name).map {|c| [c.name, c.id]}
  end
  def search
    category_id = params[:category_id]
    query = params[:query]
    @order_by = params[:order_by] || "1" # end time is default
    @order_type = params[:order_type] || "0" # asc is default
    offset = params[:offset].to_i || 0

    allegro_api = AllegroApi.instance
    options = {}
    options[:search_category] = category_id unless category_id.blank?
    options[:search_order] = @order_by
    options[:search_order_type] = @order_type
    options[:search_offset] = offset
    options[:search_price_from] = params[:price_from] || 0
    options[:search_price_to] = params[:price_to] || 0
    
    begin
      @res = allegro_api.search(query, options)
    rescue
      render json: {error: "Search failed"}, status: 500
      return
    end

    # Normally [:do_search_response][:search_array][:item] is an array
    # But when there is only one resut the allegro's API doesn't return it
    # as an array. So to keep it consistent, we put it into an array.
    if (@res[:do_search_response][:search_count].to_i > 0) && (@res[:do_search_response][:search_array][:item].is_a? Hash)
      @res[:do_search_response][:search_array][:item] = [@res[:do_search_response][:search_array][:item]]
    end

    @prev_button = nil
    @next_button = nil
    search_count = @res[:do_search_response][:search_count].to_i
    search_limit = 50 # allegro returns 50 results per page by default
    if search_count > search_limit
      if search_limit * (offset + 1) < search_count
        @next_button = offset + 1
      end
      if offset > 0
        @prev_button = offset -1
      end
    end
    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, role: 'presentation', class: class_name,) do
      link_to link_text, link_path
    end
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/auctions/index.html.erb
<h1>Saved auctions</h1>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<table>
<% @auctions.each do |a| %>
  <tr>
    <td><a href="<%= a.url %>" target="_blank"><%= a.name %></td>
    <td><%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), auction_path(a),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete this auction?' } %></td>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AllegroSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <ul class="nav nav-pills">
    <%= nav_link 'Search', root_path %>
    <%= nav_link 'My auctions', auctions_path %>
  </ul>
</nav>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/search/_pager.html.erb
<nav>
  <ul class="pager">
    <li class="previous<%= @prev_button.nil? ? ' disabled' : ''%>"><a href="#" data-offset="<%= @prev_button %>">Previous</a></li>
    <li class="next<%= @next_button.nil? ? ' disabled' : ''%>"><a href="#" data-offset="<%= @next_button %>">Next</a></li>
  </ul>
</nav>

app/views/search/index.html.erb
<h1>Allegro Search</h1>
<div>
  <p>
  <%= label_tag ('Please choose a category') %>
  <%= select_tag(:category_id, options_for_select(@categories)) %>
  </p>
  <p id="price">
  <%= label_tag ('Price') %>
  <%= text_field_tag 'price_from', nil, size: 6 %> - 
  <%= text_field_tag 'price_to', nil, size: 6 %> 
  </p>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
</div>
<div id="search_results">
</div>

app/views/search/search.html.erb
<% #@res[:do_search_response][:search_count] %>
<% if @res[:do_search_response][:search_count].to_i > 0 %>
<div class="dropdown">
  <% order_by_text = { '10' => 'Time ending ascending', '11' => 'Time ending descending',
                       '40' => 'Price ascendind', '41' => 'Price descending' } %> 
                     <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true" data-sort_by="<%= @order_by %>" data-sort_type="<%= @order_type %>">
    Sort by: <%= order_by_text[@order_by + @order_type] %>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a class="sort_by" data-sort_by='1' data-sort_type='0' role="menuitem" tabindex="-1" href="#"><%= order_by_text['10'] %></a></li>
    <li role="presentation"><a class="sort_by" data-sort_by='1' data-sort_type='1' role="menuitem" tabindex="-1" href="#"><%= order_by_text['11'] %></a></li>
    <li role="presentation"><a class="sort_by" data-sort_by='4' data-sort_type='0' role="menuitem" tabindex="-1" href="#"><%= order_by_text['40'] %></a></li>
    <li role="presentation"><a class="sort_by" data-sort_by='4' data-sort_type='1' role="menuitem" tabindex="-1" href="#"><%= order_by_text['41'] %></a></li>
  </ul>
</div>
<%= render "pager" %>
<table class='table table-bordered'>
  <% unless @res[:do_search_response][:search_array].nil? %>
    <% @res[:do_search_response][:search_array][:item].each do |item| %>
      <tr>
        <td><img src="<%= item[:s_it_thumb_url] %>"></td>
        <td><a href="http://allegro.pl/show_item.php?item=<%= item[:s_it_id] %>" target="_blank"><%= item[:s_it_name] %></a></td>
        <td><%= item[:s_it_is_buy_now] == '1' ? 'buy now ' : '' %></td>
        <td><%= item[:s_it_buy_now_price] ? item[:s_it_buy_now_price] : item[:s_it_price]  %></td>
        <td><%= time_ago_in_words(item[:s_it_time_left].to_i.seconds.from_now) %></td>
        <td><a class="add_to_my_auctions" href="#" data-url="http://allegro.pl/show_item.php?item=<%= item[:s_it_id] %>" data-name="<%= item[:s_it_name] %>">Add to my auctions</a></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= render "pager" %>
<% else %>
  <p>No results...</p>
<% end %>